[package]
name = "jsonlines"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
serde = "1.0.147"
serde_json = "1.0.87"

[dev-dependencies]
assert_fs = "1.0.7"
serde = { version = "1.0.147", features = ["derive"] }
